gnome-terminal -x "python3 agregator/toulouse_agregator.py"
gnome-terminal -x "python3 agregator/newyork_agregator.py"
gnome-terminal -x "python3 agregator/moscou_agregator.py"
gnome-terminal -x "python3 agregator/london_agregator.py"
gnome-terminal -x "python3 agregator/rio_agregator.py"