/* Generated by Scriptol */

var fs = require('fs');
var process = require('process');
var scriptol = require('p:/solj/scriptol.js');
// By Scriptol.com - This script is under MIT License

// Load a SVG file and save it as a JavaScript object in a js file
// to be loaded by an HTML page.
// The id of the svg file becomes the name of the object
// It is also the root key of the object

console.log();
console.log("SVG to JavaScript object converter by Scriptol.");

var argv = process.argv
if(argv.length < 3) {
    console.log("Syntax:  node svgtojson.js filename")
    exit(1)
}

var svgname=argv[2];
if(svgname==="") {
   scriptol.die("End");
}


var jso={};
scriptol.dLoad(jso,svgname);

var rootkey="";
for(rootkey in jso) {
   var v=String(jso[rootkey]);
   break;
}

var p=svgname.lastIndexOf(".");
var jsoname=svgname.slice(0,p+1)+"js";

var svgnode=svgname.slice(0,p);

var jsostr="var "+rootkey+"="+JSON.stringify(scriptol.clone(jso),undefined,' ');
fs.writeFileSync(jsoname,jsostr);
console.log(jsoname+' '+"saved.");
console.log();
console.log("Include it in an HTML page to be displayed in canvas");


/* End */
